modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="cmrecipes" #mandatory
version="18.03.22-1.18.1" #mandatory
displayName="CMRecipes" #mandatory
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="Cousin" #optional
description='''
Cousin's Modded Recipes (CMRecipes) is an expansive mod that adds crafting recipes for cross mod support.
'''

[[dependencies.cmrecipes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cmrecipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
